1-2-Seminar-GUI
Azarny/ch.bfh.bti7081.s2019.yellow pull request #39
Opened 2019-05-15 13:18 UTC by oppli

Beinhaltet zusätzlich den Task 4-2-FilterGUI (Einfachheitshalber gemeinsam umgesetzt).
Neue Klasse SeminarFilter für das Binding an Filter erstellt. Die Logik des Filters wird durch Michelle erstellt.

SeminarView nach MVP umgesetzt.

2019-05-15 18:35 UTC, stormrider959 requested changes
meiner Meinung nach ist das MVP-Pattern nicht korrekt umgesetzt (siehe Kommentar)

2019-05-15 18:35 UTC, stormrider959 commented on src/main/java/ch/bfh/bti7081/view/SeminarViewImpl.java
> +public class SeminarViewImpl extends VerticalLayout {
"Impl" suggeriert die Implementation eines Interfaces, was hier nicht der Fall ist
Meiner Meinung nach müsste das MVP-Pattern anders umgesetzt werden (interessant sind die Klassen CalculatorViewImpl, CalculatorPresenter und Mainview im Calculator-Beispiel)

2019-05-15 21:21 UTC, yaronwalter7 approved these changes
Finde die Umsetzung gut für eine erste Iteration, allfällige Ergänzungen kommen vermutlich eh mit der ganzen MVP-Thematik. 
Beim Mergen wird es einen Konflikt geben mit der SeminarView, dort habe ich in meinem PR einen Button für das neue Seminar eingefügt. Das File kann gut überschrieben werden, es benötigt allerdings schon noch einen Zugang zur NewSeminarView....

2019-05-15 21:21 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/model/seminar/SeminarFilter.java
> +public class SeminarFilter {
M.E. ist die Klasse eher ein DTO und wäre dorthin zu schieben und entsprechend zu benennen.

2019-05-15 21:21 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/view/SeminarViewImpl.java
> +  private void generateListLayout(){
Wow, das ist ziemlich umfangreich!
Ich kann mit der Lösung gut leben, gleichzeitig möchte ich darauf hinweisen das zumindest bei mir die Box mit den Seminaren zu lang ist, was seltsam aussieht:
![grafik](https://user-images.githubusercontent.com/48584630/57810134-64eb7480-7767-11e9-88e3-ef6baa60cb60.png)
Auch wäre es vielleicht gut die Seminare z.B. nach Datum zu sortieren.

2019-05-15 21:21 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/view/SeminarViewImpl.java
> +            event -> showDetails(event.getItem()));
Die Funktion ist cool. Wenn möglich sollte der Cursor oder das Element eine Reaktion zeigen beim Darüberfahren, so merken Benutzer allenfalls nicht das sie noch Details anschauen können. :)

2019-05-16 12:35 UTC, stormrider959 approved these changes

2019-05-16 14:15 UTC, Miishale approved these changes
ha mis druf ufbout u has intuitiv gfunge, passt für mi

2019-05-16 16:40 UTC, merged