Rework comments
Azarny/ch.bfh.bti7081.s2019.yellow pull request #62
Opened 2019-06-09 08:44 UTC by yaronwalter7

Reformat of every class in our project. 
Also, comments have been added to most methods.
(Single-Line-Methods were ignored.)

2019-06-09 09:10 UTC, Azarny commented on src/main/java/ch/bfh/bti7081/presenter/NewSeminarPresenter.java
> +     * @throws Exception different exceptions (problems with coordinates, validation)
Der google-Teil schmeisst iwie keine Exceptions, hatte gestern vergessen den Key hinzuzufügen, und man kriegts nicht mit, es funktioniert einfach nicht

2019-06-09 09:21 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/presenter/NewSeminarPresenter.java
> +     * @throws Exception different exceptions (problems with coordinates, validation)
Kann ich so nicht bestätigen. 
Kommentiert man den Key aus, wird beim Resolven der Koordinaten die Erstellung abgebrochen -> Systemfehler-Warnung wird dem Benutzer angezeigt...

2019-06-09 09:46 UTC, Miishale requested changes
Wenis bi mir abezie und builde und starte chunnt weni uf d site ga folgendi Errormeldig:
Error creating bean with name 'ch.bfh.bti7081.view.MainView': Invocation of init method failed; nested exception is org.springframework.orm.jpa.JpaSystemException: No default constructor for entity:  : ch.bfh.bti7081.model.seminar.SeminarCategory;

Weni bi SeminarCategory ner dr Konstruktor public SeminarCategory(){}; hinzuefüege geits. Auso vilech ha o i fähler gmacht...

2019-06-09 09:46 UTC, Miishale commented on src/main/java/ch/bfh/bti7081/model/seminar/SeminarFilter.java
> +     * @author luscm1
ds het dr simu gschribe gloub

2019-06-09 09:46 UTC, Miishale commented on src/main/java/ch/bfh/bti7081/presenter/dto/ForumEntryDTO.java
> + * @author luscms1
typo, luscm1 heissi :D

2019-06-09 09:46 UTC, Miishale commented on src/main/java/ch/bfh/bti7081/presenter/dto/ForumEntryDTO.java
> + * @author luscms1
u dsch gloub nid vo mir. bimer aber nid sicher

2019-06-09 09:46 UTC, Miishale commented on src/main/java/ch/bfh/bti7081/view/customComponents/GoogleMap.java
> +    public void setZoomLevel(int level) {
bruchts hie keni javadoc blöck?

2019-06-09 10:07 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/view/customComponents/GoogleMap.java
> +    public void setZoomLevel(int level) {
M.E. nicht, es handelt sich um One-Liner...

2019-06-09 10:08 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/presenter/dto/ForumEntryDTO.java
> + * @author luscms1
Naja, bitte selber apasse, es isch ned würk min Task...

2019-06-09 10:16 UTC, yaronwalter7 commented on src/main/java/ch/bfh/bti7081/view/customComponents/GoogleMap.java
> +    public void setZoomLevel(int level) {
Habe jetzt doch einen gemacht, da ich gesehen habe das es Fragen stellen könnte. :)

2019-06-09 12:37 UTC, Miishale commented on src/main/java/ch/bfh/bti7081/model/seminar/SeminarFilter.java
> +     * @author luscm1
angepasst

2019-06-09 12:38 UTC, Miishale commented on src/main/java/ch/bfh/bti7081/presenter/dto/ForumEntryDTO.java
> + * @author luscms1
recht hesch, has gmacht

2019-06-09 12:39 UTC, Miishale approved these changes
Passt iz (y)

2019-06-10 09:08 UTC, oppli commented on src/main/java/ch/bfh/bti7081/view/SeminarView.java
> +     * The filter on the frontend is bound to a SeminarFilter object.
Neu SeminarFilterDTO

2019-06-10 09:10 UTC, oppli approved these changes

2019-06-10 11:16 UTC, merged